trigger:
  branches:
    include:
      - streamlabs
  tags:
    include:
      - '*'

variables:
  BuildDirectory: build
  Generator: Visual Studio 15 2017 Win64
  DistributeDirectory: distribute
  FullDistributePath: $(BuildDirectory)\$(DistributeDirectory)
  RuntimeURL: https://artifacts.electronjs.org/headers/dist
  RuntimeName: iojs
  RuntimeVersion: v25.9.3

jobs:
- job: 'MacOSX'
  pool:
    vmImage: 'macos-11'
  strategy:
    matrix:
      release-x86_64:
        arch: x86_64
      release-arm64:
        arch: arm64
  workspace:
    clean: all

  steps:
  - checkout: self
    fetchDepth: 10

  - powershell: 'Write-Host "##vso[task.setvariable variable=tagartifact]node-window-rendering-$((git describe --tags --abbrev=0) | Out-String)"'
    displayName: 'Get tag for artifact'

  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '10.x'

  - script: 'yarn install'
    displayName: 'Install dependencies'

  - script: 'node ci/bump-version.js'
    displayName: 'Bump version number'
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))

  - script: './ci/build-osx.sh'
    displayName: 'Build node-window-rendering'
    env:
      ARCHITECTURE: $(arch)

  - task: ArchiveFiles@2
    displayName: 'Generate artifact'
    inputs:
      rootFolderOrFile: build/distribute/node-window-rendering
      includeRootFolder: true
      archiveType: tar
      tarCompression: gz
      archiveFile: '$(tagartifact)-osx-$(arch).tar.gz'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifact'
    inputs: 
      pathtoPublish: $(Build.SourcesDirectory)/$(tagartifact)-osx-$(arch).tar.gz
      artifactName: $(tagartifact)-osx-$(arch).tar.gz

  - task: S3Upload@1
    inputs:
      awsCredentials: 'Streamlabs AWS'
      regionName: 'us-west-2'
      bucketName: 'slobs-node-window-rendering'
      globExpressions: '$(tagartifact)-osx-$(arch).tar.gz'
      filesAcl: 'public-read'
    displayName: 'Upload tag artifact to S3'
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
